steps:
  # 1. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 2. Terraform Apply
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']
    dir: 'terraform'

  # 3. Trigger Cloud Storage Transfer Job (GCS bucket replication)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: [
      'transfer', 'jobs', 'run',
      '5103117432597975895'
    ]
options:
  logging: CLOUD_LOGGING_ONLY

